services:
  - type: web
    name: gaming-store-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn src.main:app"
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: src/main.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
  - type: static
    name: gaming-store-frontend
    buildCommand: "echo 'No build command for static site'"
    staticPublishPath: frontend
    rootDir: frontend

